### ISSUE TITLE
Avoid license violation

### ISSUE THREAD

**Issue by pixeldesu** [modernspring/retrospring#1]
Modernspring is violating Retrosprings origin license, AGPLv3, since commit b0374ad320f7dcf1c6396d14c6da100fb1565145 with having a vital part of the source removed from the repository.

We are referring to following paragraph of the license:
```
6. Conveying Non-Source Forms.

 You may convey a covered work in object code form under the terms
of sections 4 and 5, provided that you also convey the
machine-readable Corresponding Source under the terms of this License,
in one of these ways:

b) Convey the object code in, or embodied in, a physical product
   (including a physical distribution medium), accompanied by a
   written offer, valid for at least three years and valid for as
   long as you offer spare parts or customer support for that product
   model, to give anyone who possesses the object code either (1) a
   copy of the Corresponding Source for all the software in the
   product that is covered by this License, on a durable physical
   medium customarily used for software interchange, for a price no
   more than your reasonable cost of physically performing this
   conveying of source, or (2) access to copy the
   Corresponding Source from a network server at no charge.
```

The `config/` folder is vital to any Ruby on Rails installation, as it not just includes database and application level configuration, but also initializers for internal and external tools. Without this, it's technically impossible for anyone to run and contribute to Modernspring in it's own.

While Retrospring encourages open source contributions and forks, this one clearly violates the license, and if nothing is done to comply to it we have to take legal action.

**Comment by SEAPUNK** [comment]
bc99b0300be9ea03f11eb4d7669dc034ce8b162b
